### ISSUE TITLE
Class'lar

### ISSUE THREAD

**Issue by sefaun** [iremsimsar/libraryApp#1]
Neden oluşturduğun bütün `class`ların metodları `static`. Madem `static` yapacağız neden `class` kullanim ?

**Comment by iremsimsar** [comment]
Static method  oluşturdugun zaman dışarıdan object yaratmadan kullanabilirsin bu yüzden static olarak oluşturdum. Hepsi statik değil sadece implemente edilmeyen yerlerde statik.

**Comment by sefaun** [comment]
sen biraz oop yapmaya zorlamışsın. :)

**Comment by iremsimsar** [comment]
kime göre neye göre ?

**Comment by sefaun** [comment]
Başka yollarla da yapabilirsin çünkü. Ama sen class tercih etmişsin o yüzden 😊

**Comment by sefaun** [comment]
Başka yollarla da yapabilirsin çünkü. Ama sen class tercih etmişsin o yüzden 😊

**Comment by sefaun** [comment]
Başka yollarla da yapabilirsin çünkü. Ama sen class tercih etmişsin o yüzden

**Comment by sefaun** [comment]
Güzel bir yöntem şimdi farkettim. Teşekkürler.
